export const australianChampionsATP = {
	headers: ["Year", "Champion", "Runner-Up", "Score"],
	options: [
		{
			id: 1,
			year: "2024",
			champion: "Jannik Sinner (ITA)",
			runnerup: "Daniil Medvedev",
			score: "3-6, 3-6, 6-4, 6-4, 6-3",
		},
		{
			id: 2,
			year: "2023",
			champion: "Novak Djokovic (SRB)",
			runnerup: "Stefanos Tsitsipas (GRE)",
			score: "6-3, 7-6(4), 7-6(5)",
		},
		{
			id: 3,
			year: "2022",
			champion: "Rafael Nadal (ESP)",
			runnerup: "Daniil Medvedev",
			score: "2-6, 6-7(5), 6-4, 6-4, 7-5",
		},
		{
			id: 4,
			year: "2021",
			champion: "Novak Djokovic (SRB)",
			runnerup: "Daniil Medvedev",
			score: "7-5, 6-2, 6-2",
		},
		{
			id: 5,
			year: "2020",
			champion: "Novak Djokovic (SRB)",
			runnerup: "Dominic Thiem (AUT)",
			score: "6-4, 4-6, 2-6, 6-3, 6-4",
		},
		{
			id: 6,
			year: "2019",
			champion: "Novak Djokovic (SRB)",
			runnerup: "Rafael Nadal (ESP)",
			score: "6-3, 6-2, 6-3",
		},
		{
			id: 7,
			year: "2018",
			champion: "Roger Federer (SUI)",
			runnerup: "Marin Cilic (CRO)",
			score: "6-2, 6-7(5), 6-3, 3-6, 6-1",
		},
		{
			id: 8,
			year: "2017",
			champion: "Roger Federer (SUI)",
			runnerup: "Rafael Nadal (ESP)",
			score: "6-4, 3-6, 6-1, 3-6, 6-3",
		},
		{
			id: 9,
			year: "2016",
			champion: "Novak Djokovic (SRB)",
			runnerup: "Andy Murray (GBR)",
			score: "6-1, 7-5, 7-6(3)",
		},
		{
			id: 10,
			year: "2015",
			champion: "Novak Djokovic (SRB)",
			runnerup: "Andy Murray (GBR)",
			score: "7-6(5), 6-7(4), 6-3, 6-0",
		},
	],
};

export const australianChampionsWTA = {
	headers: ["Year", "Champion", "Runner-Up", "Score"],
	options: [
		{
			id: 1,
			year: "2024",
			champion: "Aryna Sabalenka",
			runnerup: "Zheng Qinwen (CHN)",
			score: "6-3, 6-2",
		},
		{
			id: 2,
			year: "2023",
			champion: "Aryna Sabalenka",
			runnerup: "Elena Rybakina (KAZ)",
			score: "4-6, 6-3, 6-4",
		},
		{
			id: 3,
			year: "2022",
			champion: "Ashleigh Barty (AUS)",
			runnerup: "Danielle Collins (USA)",
			score: "6-3, 7-6(2)",
		},
		{
			id: 4,
			year: "2021",
			champion: "Naomi Osaka (JPN)",
			runnerup: "Jennifer Brady (USA)",
			score: "6-4, 6-3",
		},
		{
			id: 5,
			year: "2020",
			champion: "Sofia Kenin (USA)",
			runnerup: "Garbine Muguruza (ESP)",
			score: "4-6, 6-2, 6-2",
		},
		{
			id: 6,
			year: "2019",
			champion: "Naomi Osaka (JPN)",
			runnerup: "Petra Kvitova (CZE)",
			score: "7-6(2), 5-7, 6-4",
		},
		{
			id: 7,
			year: "2018",
			champion: "Caroline Wozniacki (DEN)",
			runnerup: "Simona Halep (ROU)",
			score: "7-6(2), 3-6, 6-4",
		},
		{
			id: 8,
			year: "2017",
			champion: "Serena Williams (USA)",
			runnerup: "Venus Williams (USA)",
			score: "6-4, 6-4",
		},
		{
			id: 9,
			year: "2016",
			champion: "Angelique Kerber (GER)",
			runnerup: "Serena Williams (USA)",
			score: "6-4, 3-6, 6-4",
		},
		{
			id: 10,
			year: "2015",
			champion: "Serena Williams (USA)",
			runnerup: "Maria Sharapova",
			score: "6-3, 7-6(5)",
		},
	],
};

export const frenchChampionsATP = {
	headers: ["Year", "Champion", "Runner-Up", "Score"],
	options: [
		{
			id: 1,
			year: "2024",
			champion: "Carlos Alcaraz (ESP)",
			runnerup: "Alexander Zverev",
			score: "6-3, 2-6, 5-7, 6-1, 6-2",
		},
		{
			id: 2,
			year: "2023",
			champion: "Novak Djokovic (SRB)",
			runnerup: "Casper Ruud (NOR)",
			score: "7-6(1), 6-3, 7-5",
		},
		{
			id: 3,
			year: "2022",
			champion: "Rafael Nadal (ESP)",
			runnerup: "Casper Ruud (NOR)",
			score: "6-3, 6-3, 6-0",
		},
		{
			id: 4,
			year: "2021",
			champion: "Novak Djokovic (SRB)",
			runnerup: "Stefanos Tsitsipas (GRE)",
			score: "6-7(6), 2-6, 6-3, 6-2, 6-4",
		},
		{
			id: 5,
			year: "2020",
			champion: "Rafael Nadal (ESP)",
			runnerup: "Novak Djokovic (SRB)",
			score: "6-0, 6-2, 7-5",
		},
		{
			id: 6,
			year: "2019",
			champion: "Rafael Nadal (ESP)",
			runnerup: "Dominic Thiem (AUT)",
			score: "6-3, 5-7, 6-1, 6-1",
		},
		{
			id: 7,
			year: "2018",
			champion: "Rafael Nadal (ESP)",
			runnerup: "Dominic Thiem (AUT)",
			score: "6-4, 6-3, 6-2",
		},
		{
			id: 8,
			year: "2017",
			champion: "Rafael Nadal (ESP)",
			runnerup: "Stan Wawrinka (SUI)",
			score: "6-2, 6-3, 6-1",
		},
		{
			id: 9,
			year: "2016",
			champion: "Novak Djokovic (SRB)",
			runnerup: "Andy Murray (GBR)",
			score: "3-6, 6-1, 6-2, 6-4",
		},
		{
			id: 10,
			year: "2015",
			champion: "Stan Wawrinka (SUI)",
			runnerup: "Novak Djokovic (SRB)",
			score: "4-6, 6-4, 6-3, 6-4",
		},
	],
};

export const frenchChampionsWTA = {
	headers: ["Year", "Champion", "Runner-Up", "Score"],
	options: [
		{
			id: 1,
			year: "2024",
			champion: "Iga Swiatek (POL)",
			runnerup: "Jasmine Paolini (ITA)",
			score: "6-2, 6-1",
		},
		{
			id: 2,
			year: "2023",
			champion: "Iga Swiatek (POL)",
			runnerup: "Karolina Muchova (CZE)",
			score: "6-2, 5-7, 6-4",
		},
		{
			id: 3,
			year: "2022",
			champion: "Iga Swiatek (POL)",
			runnerup: "Coco Gauff (USA)",
			score: "6-1, 6-3",
		},
		{
			id: 4,
			year: "2021",
			champion: "Barbora Krejcikova (CZE)",
			runnerup: "Anastasia Pavlyuchenkova (RUS)",
			score: "6-1, 2-6, 6-4",
		},
		{
			id: 5,
			year: "2020",
			champion: "Iga Swiatek (POL)",
			runnerup: "Sofai Kenin (USA)",
			score: "6-4, 6-1",
		},
		{
			id: 6,
			year: "2019",
			champion: "Ashleigh Barty (AUS)",
			runnerup: "Marketa Vondrousova (CZE)",
			score: "6-1, 6-3",
		},
		{
			id: 7,
			year: "2018",
			champion: "Simona Halep (ROU)",
			runnerup: "Sloane Stephens (USA)",
			score: "3-6, 6-4, 6-1",
		},
		{
			id: 8,
			year: "2017",
			champion: "Jelena Ostapenko (LAT)",
			runnerup: "Simona Halep (ROU)",
			score: "4-6, 6-4, 6-3",
		},
		{
			id: 9,
			year: "2016",
			champion: "Garbine Muguruza (ESP)",
			runnerup: "Serena Williams (USA)",
			score: "7-5, 6-4",
		},
		{
			id: 10,
			year: "2015",
			champion: "Serena Williams (USA)",
			runnerup: "Lucie Safarova (CZE)",
			score: "6-3, 6-7(2), 6-2",
		},
	],
};
