export const streamingData = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Tennis Channel Plus",
			location: "USA",
			cost: "$109.99/year",
			details: "No monthly plan available currently",
		},
		{
			id: 8,
			name: "T2",
			location: "USA",
			cost: "Free",
			details: "Available via Samsung TV and Youtube TV",
		},
		{
			id: 9,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
		{
			id: 10,
			name: "BBC iPlayer",
			location: "UK",
			cost: "Free",
			details: "",
		},
	],
};

export const streamingDataAO = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
	],
};

export const streamingDataFO = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "NBC Sports",
			location: "USA",
			cost: "Free",
			details: "",
		},
		{
			id: 6,
			name: "Peacock",
			location: "USA",
			cost: "$5.99",
			details:
				"Also available to SKY and NOW subscribers in UK, Germany, Austria, Switzerland, Italy, or Ireland",
		},
		{
			id: 7,
			name: "ITV Hub",
			location: "UK",
			cost: "Free",
			details: "",
		},
		{
			id: 8,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
	],
};

export const streamingDataWimbledon = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
		{
			id: 8,
			name: "BBC iPlayer",
			location: "UK",
			cost: "Free",
			details: "",
		},
	],
};

export const atpTournamentData = {
	headers: ["Date", "Tournament", "ATP Level", "Location"],
	options: [
		{
			id: 1,
			date: "Dec. 29 - Jan. 7",
			tournament: "United Cup",
			level: "N/A",
			location: "Perth-Sydney, Australia",
		},
		{
			id: 2,
			date: "Dec. 31 - Jan. 7",
			tournament: "Brisbane International",
			level: "250",
			location: "Brisbane, Australia",
		},
		{
			id: 3,
			date: "Jan. 1 - Jan. 7",
			tournament: "Hong Kong Open",
			level: "250",
			location: "Hong Kong",
		},
		{
			id: 4,
			date: "Jan. 8 - Jan. 13",
			tournament: "Adelaide International",
			level: "250",
			location: "Adelaide, Australia",
		},
		{
			id: 5,
			date: "Jan. 8 - Jan. 13",
			tournament: "ASB Classic",
			level: "250",
			location: "Auckland, New Zealand",
		},
		{
			id: 6,
			date: "Jan. 14 - Jan. 28",
			tournament: "Australian Open",
			level: "Grand Slam",
			location: "Melbourne, Australia",
		},
		{
			id: 7,
			date: "Jan. 29 - Feb. 4",
			tournament: "Open Sud de France",
			level: "250",
			location: "Montpellier, France",
		},
		{
			id: 8,
			date: "Feb. 5 - Feb. 11",
			tournament: "Cordoba Open",
			level: "250",
			location: "Cordoba, Argentina",
		},
		{
			id: 9,
			date: "Feb. 5 - Feb. 11",
			tournament: "Dallas Open",
			level: "250",
			location: "Dallas, Texas",
		},
		{
			id: 10,
			date: "Feb. 5 - Feb. 11",
			tournament: "Open 13 Provence",
			level: "250",
			location: "Marseille, France",
		},
	],
};

export const wtaTournamentData = {
	headers: ["Date", "Tournament", "WTA Level", "Location"],
	options: [
		{
			id: 1,
			date: "Dec. 29 - Jan. 7",
			tournament: "United Cup",
			level: "500",
			location: "Perth-Sydney, Australia",
		},
		{
			id: 2,
			date: "Jan. 1 - Jan. 6",
			tournament: "Canberra Open",
			level: "125",
			location: "Canberra, Australia",
		},
		{
			id: 3,
			date: "Jan. 1 - Jan. 7",
			tournament: "Brisbane International",
			level: "500",
			location: "Brisbane, Australia",
		},
		{
			id: 4,
			date: "Jan. 1 - Jan. 7",
			tournament: "ASB Classic",
			level: "250",
			location: "Auckland, New Zealand",
		},
		{
			id: 5,
			date: "Jan. 8 - Jan. 13",
			tournament: "Hobart International",
			level: "250",
			location: "Hobart, Australia",
		},
		{
			id: 6,
			date: "Jan. 8 - Jan. 13",
			tournament: "Adelaide International",
			level: "500",
			location: "Adelaide, Australia",
		},
		{
			id: 7,
			date: "Jan. 14 - Jan. 28",
			tournament: "Australian Open",
			level: "Grand Slam",
			location: "Melbourne, Australia",
		},
		{
			id: 8,
			date: "Jan. 22 - Jan. 28",
			tournament: "Da Nang Open",
			level: "125",
			location: "Da Nang, Vietnam",
		},
		{
			id: 9,
			date: "Jan. 29 - Feb. 4",
			tournament: "Upper Austria Ladies Linz",
			level: "500",
			location: "Linz, Austria",
		},
		{
			id: 10,
			date: "Jan. 29 - Feb. 4",
			tournament: "Thailand Open",
			level: "250",
			location: "Hua Hin, Thailand",
		},
	],
};
