export const streamingData = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Tennis Channel Plus",
			location: "USA",
			cost: "$109.99/year",
			details: "No monthly plan available currently",
		},
		{
			id: 8,
			name: "T2",
			location: "USA",
			cost: "Free",
			details: "Available via Samsung TV and Youtube TV",
		},
		{
			id: 9,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
		{
			id: 10,
			name: "BBC iPlayer",
			location: "UK",
			cost: "Free",
			details: "",
		},
	],
};

export const streamingDataAO = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
	],
};

export const streamingDataFO = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "NBC Sports",
			location: "USA",
			cost: "Free",
			details: "",
		},
		{
			id: 6,
			name: "Peacock",
			location: "USA",
			cost: "$5.99",
			details:
				"Also available to SKY and NOW subscribers in UK, Germany, Austria, Switzerland, Italy, or Ireland",
		},
		{
			id: 7,
			name: "ITV Hub",
			location: "UK",
			cost: "Free",
			details: "",
		},
		{
			id: 8,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
	],
};

export const streamingDataWimbledon = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
		{
			id: 8,
			name: "BBC iPlayer",
			location: "UK",
			cost: "Free",
			details: "",
		},
	],
};

export const streamingDataUSO = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
	],
};

export const atpTournamentData = {
	headers: ["Date", "Tournament", "ATP Level", "Location"],
	options: [
		{
			id: 1,
			date: "Jun. 23 - Jun. 29",
			tournament: "Mallorca Championships",
			level: "250",
			location: "Mallorca, Spain",
		},
		{
			id: 2,
			date: "Jun. 24 - Jun. 29",
			tournament: "Rothesay International",
			level: "250",
			location: "Eastbourne, Great Britain",
		},
		{
			id: 3,
			date: "Jul. 1 - Jul. 14",
			tournament: "Wimbledon",
			level: "Grand Slam",
			location: "London, Great Britain",
		},
		{
			id: 4,
			date: "Jul. 15 - Jul. 21",
			tournament: "Hamburg Open",
			level: "500",
			location: "Hamburg, Germany",
		},
		{
			id: 5,
			date: "",
			tournament: "Infosys Hall of Fame Open",
			level: "250",
			location: "Newport, USA",
		},
		{
			id: 6,
			date: "",
			tournament: "EFG Swiss Open",
			level: "250",
			location: "Gstaad, Switzerland",
		},
		{
			id: 7,
			date: "",
			tournament: "Nordea Open",
			level: "250",
			location: "Bastad, Sweden",
		},
		{
			id: 8,
			date: "Jul. 21 - Jul. 27",
			tournament: "Plava Laguna Croatia Open",
			level: "250",
			location: "Umag, Croatia",
		},
		{
			id: 9,
			date: "Jul. 22 - Jul. 28",
			tournament: "Atlanta Open",
			level: "250",
			location: "Atlanta, USA",
		},
		{
			id: 10,
			date: "Jul. 22 - Jul. 27",
			tournament: "Generali Open",
			level: "250",
			location: "Kitzbuhel, Austria",
		},
	],
};

export const wtaTournamentData = {
	headers: ["Date", "Tournament", "WTA Level", "Location"],
	options: [
		{
			id: 1,
			date: "Jun. 23 - Jun. 29",
			tournament: "Bad Homburg Open",
			level: "500",
			location: "Bad Homburg, Germany",
		},
		{
			id: 2,
			date: "Jun. 24 - Jun. 29",
			tournament: "Rothesay International",
			level: "500",
			location: "Eastbourne, Great Britain",
		},
		{
			id: 3,
			date: "Jul. 1 - Jul. 14",
			tournament: "Wimbledon",
			level: "Grand Slam",
			location: "London, Great Britain",
		},
		{
			id: 4,
			date: "Jul. 8 - Jul. 14",
			tournament: "Grand Est Open 88",
			level: "125",
			location: "Contrexeville, France",
		},
		{
			id: 5,
			date: "Jul. 8 - Jul. 13",
			tournament: "Nordea Open",
			level: "125",
			location: "Bastad, Sweden",
		},
		{
			id: 6,
			date: "Jul. 15 - Jul. 21",
			tournament: "Hungarian Grand Prix",
			level: "250",
			location: "Budapest, Hungary",
		},
		{
			id: 7,
			date: "",
			tournament: "Palermo Ladies Open",
			level: "250",
			location: "Palermo, Italy",
		},
		{
			id: 8,
			date: "Jul. 21 - Jul. 26",
			tournament: "UniCredit Iasi Open",
			level: "250",
			location: "Iasi, Romania",
		},
		{
			id: 9,
			date: "",
			tournament: "Livesport Prague Open",
			level: "250",
			location: "Prague, Czech Republic",
		},
		{
			id: 10,
			date: "Jul. 22 - Jul. 27",
			tournament: "Polish Open",
			level: "125",
			location: "Warsaw, Poland",
		},
	],
};
