export const streamingData = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Tennis Channel Plus",
			location: "USA",
			cost: "$109.99/year",
			details: "No monthly plan available currently",
		},
		{
			id: 8,
			name: "T2",
			location: "USA",
			cost: "Free",
			details: "Available via Samsung TV and Youtube TV",
		},
		{
			id: 9,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
		{
			id: 10,
			name: "BBC iPlayer",
			location: "UK",
			cost: "Free",
			details: "",
		},
	],
};

export const streamingDataAO = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
	],
};

export const streamingDataFO = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "NBC Sports",
			location: "USA",
			cost: "Free",
			details: "",
		},
		{
			id: 6,
			name: "Peacock",
			location: "USA",
			cost: "$5.99",
			details:
				"Also available to SKY and NOW subscribers in UK, Germany, Austria, Switzerland, Italy, or Ireland",
		},
		{
			id: 7,
			name: "ITV Hub",
			location: "UK",
			cost: "Free",
			details: "",
		},
		{
			id: 8,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
	],
};

export const streamingDataWimbledon = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
		{
			id: 8,
			name: "BBC iPlayer",
			location: "UK",
			cost: "Free",
			details: "",
		},
	],
};

export const streamingDataUSO = {
	headers: ["Streaming service", "Availability", "Cost per month", "Streaming details"],
	options: [
		{
			id: 1,
			name: "9Now",
			location: "Australia",
			cost: "Free",
			details: "",
		},
		{
			id: 2,
			name: "Stan Sport",
			location: "Australia",
			cost: "$15",
			details: "Requires Stan Basic which starts at $10/month (with 30 day free trial).",
		},
		{
			id: 3,
			name: "TSN",
			location: "Canada",
			cost: "$19.99",
			details: "TSN1 - TSN5, TSN+",
		},
		{
			id: 4,
			name: "Star+",
			location: "Latin America",
			cost: "$9.99",
			details: "",
		},
		{
			id: 5,
			name: "ESPN+",
			location: "USA",
			cost: "$9.99",
			details: "",
		},
		{
			id: 6,
			name: "Sling TV",
			location: "USA",
			cost: "$40 ($20 first month)",
			details: "ESPN, ESPN2, ESPN3",
		},
		{
			id: 7,
			name: "Eurosport",
			location: "UK",
			cost: "\u00A3" + "6.99",
			details: "Subscribe via Discovery+",
		},
	],
};

export const atpTournamentData = {
	headers: ["Date", "Tournament", "ATP Level", "Location"],
	options: [
		{
			id: 1,
			date: "Aug. 6 - Aug. 12",
			tournament: "National Bank Open",
			level: "1000",
			location: "Montreal, Canada",
		},
		{
			id: 2,
			date: "Aug. 12 - Aug. 19",
			tournament: "Cincinnati Open",
			level: "1000",
			location: "Cincinnati, Ohio (USA)",
		},
		{
			id: 3,
			date: "Aug. 18 - Aug. 24",
			tournament: "Winston-Salem Open",
			level: "250",
			location: "Winston-Salem, North Carolina (USA)",
		},
		{
			id: 4,
			date: "Aug. 26 - Sep. 8",
			tournament: "US Open",
			level: "Grand Slam",
			location: "Flushing, New York (USA)",
		},
		{
			id: 5,
			date: "Sep. 18 - Sep. 24",
			tournament: "Chengdu Open",
			level: "250",
			location: "Chengdu, China",
		},
		{
			id: 6,
			date: "",
			tournament: "Hangzhou Open",
			level: "250",
			location: "Hangzhou, China",
		},
		{
			id: 7,
			date: "Sep. 20 - Sep. 22",
			tournament: "Laver Cup",
			level: "---",
			location: "Berlin, Germany",
		},
		{
			id: 8,
			date: "Sep. 25 - Oct. 1",
			tournament: "Japan Open",
			level: "500",
			location: "Tokyo, Japan",
		},
		{
			id: 9,
			date: "Sep. 26 - Oct. 2",
			tournament: "China Open",
			level: "500",
			location: "Beijing, China",
		},
		{
			id: 10,
			date: "Oct. 2 - Oct. 13",
			tournament: "Rolex Shanghai Masters",
			level: "1000",
			location: "Shanghai, China",
		},
	],
};

export const wtaTournamentData = {
	headers: ["Date", "Tournament", "WTA Level", "Location"],
	options: [
		{
			id: 1,
			date: "Aug. 6 - Aug. 12",
			tournament: "National Bank Open",
			level: "1000",
			location: "Toronto, Canada",
		},
		{
			id: 2,
			date: "Aug. 12 - Aug. 17",
			tournament: "Barranquilla Open",
			level: "125",
			location: "Barranquilla, Colombia",
		},
		{
			id: 3,
			date: "Aug. 13 - Aug. 19",
			tournament: "Cincinnati Open",
			level: "1000",
			location: "Cincinnati, Ohio (USA)",
		},
		{
			id: 4,
			date: "Aug. 18 - Aug. 24",
			tournament: "Tennis in the Land",
			level: "250",
			location: "Cleveland, Ohio (USA)",
		},
		{
			id: 5,
			date: "",
			tournament: "Abierto GNP Seguros",
			level: "500",
			location: "Monterrey, Mexico",
		},
		{
			id: 6,
			date: "Aug. 26 - Sep. 8",
			tournament: "US Open",
			level: "Grand Slam",
			location: "Flushing, New York (USA)",
		},
		{
			id: 7,
			date: "Sep. 2 - Sep. 8",
			tournament: "Montreux Nestle Open",
			level: "125",
			location: "Montreux, Switzerland",
		},
		{
			id: 8,
			date: "",
			tournament: "Guadalajara 125 Open",
			level: "125",
			location: "Guadalajara, Mexico",
		},
		{
			id: 9,
			date: "Sep. 9 - Sep. 15",
			tournament: "Zavarovalnica Sava Ljubljana",
			level: "125",
			location: "Ljubljana, Slovenia",
		},
		{
			id: 10,
			date: "",
			tournament: "Jasmin Open",
			level: "250",
			location: "Monastir, Tunisia",
		},
		{
			id: 11,
			date: "",
			tournament: "Guadalajara Open",
			level: "500",
			location: "Guadalajara, Mexico",
		},
		{
			id: 12,
			date: "",
			tournament: "Tiriac Foundation Trophy",
			level: "125",
			location: "Bucharest, Romania",
		},
	],
};
